version: "3"
services:
  database:
    image: postgres:14.17-alpine3.21
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dynamika_assignment
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
